### ISSUE TITLE
Configure image versions in charts like we do for openfaas/inlets-operator

### ISSUE THREAD

**Issue by alexellis** [inlets/inlets-pro#44]
Configure image versions in charts like we do for openfaas/inlets-operator

From:

```
image:
  repository: ghcr.io/inlets/inlets-pro
  pullPolicy: IfNotPresent
  tag: "0.9.23"
```

To:

```
image: ghcr.io/inlets/inlets-pro:9.9.23
pullPolicy: IfNotPresent
```

If there is more than one image in the values.yaml, then break out like:

```
component1:
  image:
component2:
  image:

pullPolicy: Always
```
